// Prop shapes generated by Typelizer from the Alba resources in app/serializers.
// The generated files import each other through '@/types', so they must be re-exported here.
export * from './generated';

export type FlashData = {
  notice?: string | null;
  alert?: string | null;
};

// The signed-in admin (Admin::BaseController `inertia_share`), on the admin pages only.
export type CurrentUser = {
  email: string;
  fullName: string;
};

// The Chile Tech Week a page is about (Admin::BaseController `inertia_share`), on the admin
// pages only: `slug` is the "26" in /admin/26.
export type AdminWeek = {
  slug: string;
  year: number;
};

// Props shared with every Inertia page (see ApplicationController `inertia_share`).
export type SharedProps = {
  flash: FlashData;
  currentUser?: CurrentUser | null;
  week?: AdminWeek | null;
  weeks?: AdminWeek[];
};
