// Prop shapes generated by Typelizer from the Alba resources in app/serializers.
// The generated files import each other through '@/types', so they must be re-exported here.
export * from './generated';

export type FlashData = {
  notice?: string | null;
  alert?: string | null;
};

// Props shared with every Inertia page (see ApplicationController `inertia_share`).
export type SharedProps = {
  flash: FlashData;
};
