// Prop shapes generated by Typelizer from the Alba resources in app/serializers.
// The generated files import each other through '@/types', so they must be re-exported here.
export * from './generated';

export type FlashData = {
  notice?: string | null;
  alert?: string | null;
};

// The signed-in admin (Admin::BaseController `inertia_share`), on the admin pages only.
export type CurrentUser = {
  email: string;
  fullName: string;
};

// The Chile Tech Week a page is about (Admin::BaseController `inertia_share`), on the admin
// pages only: `slug` is the "26" in /admin/26.
export type AdminWeek = {
  slug: string;
  year: number;
};

// The public site's two languages (Localized `inertia_share`), on its pages only: the same
// page in each language, and the one to offer a visitor who has not chosen, if any.
export type LocaleSwitch = {
  alternates: Record<'es' | 'en', string>;
  suggestion: 'es' | 'en' | null;
};

// Props shared with every Inertia page (see ApplicationController `inertia_share`).
export type SharedProps = {
  flash: FlashData;
  locale: 'es' | 'en';
  localeSwitch?: LocaleSwitch;
  currentUser?: CurrentUser | null;
  week?: AdminWeek | null;
  weeks?: AdminWeek[];
};

// /events/new?luma=<link>: the form for the link ("ask"), why a link cannot be used ("error"),
// or the Luma event found ("ok"), whose data prefills the form (EventsController#lookup_luma).
export type LumaImport = {
  state: 'ask' | 'error' | 'ok';
  url: string;
  error?: string;
  message?: string;
  event?: { title: string; url: string; cover_url: string | null; starts_at: string; ends_at: string };
};

// The development-only prefill of /events/new (EventsController#prefill_from_url), keyed by
// the form's own param names.
export type EventPrefill = Partial<Record<string, string> & { theme_ids: string[]; audience_ids: string[] }>;
