import { expect, test } from '@playwright/test';
import { fillOrganizer, fillEventDetails } from './event-form';

test('validates on blur, clears corrected errors, and rechecks dependent dates and selections', async ({ page }) => {
  await page.goto('/events/new');
  const email = page.getByLabel('Email de contacto').first();
  await email.fill('bad');
  await expect(page.locator('#author_email-error')).toHaveCount(0);
  await email.blur();
  await expect(email).toHaveAttribute('aria-invalid', 'true');
  await expect(page.locator('#author_email-error')).toHaveText('Ingresa un email válido.');
  await email.fill('ada@platan.us');
  await expect(page.locator('#author_email-error')).toHaveCount(0);
  await fillOrganizer(page);
  await page.getByLabel('Sitio web').first().fill('http://platan.us');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await expect(page.locator('#company_website-error')).toContainText('https://');
  await page.getByLabel('Sitio web').first().fill('https://platan.us');
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await expect(page.locator('#commune-error')).toBeVisible();
  await fillEventDetails(page);
  await expect(page.locator('#commune-error')).toHaveCount(0);
  await expect(page.locator('#format-error')).toHaveCount(0);
  await page.getByLabel('Capacidad').fill('500001');
  await expect(page.locator('#capacity-error')).toBeVisible();
  await page.getByLabel('Capacidad').fill('10');
  await page.getByLabel('Término').fill('2026-11-18T17:00');
  await expect(page.locator('#ends_at-error')).toContainText('después');
  await page.getByLabel('Inicio').fill('2026-11-18T16:00');
  await expect(page.locator('#ends_at-error')).toHaveCount(0);
  await page.getByLabel('Logo de la empresa').setInputFiles('spec/fixtures/files/logo-quality.png');
  await expect(page.getByText(/400 × 400 px/)).toBeVisible();
  await expect(page.getByText('Selecciona el logo de la empresa.')).toHaveCount(0);
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Continuar' }).click();
  await expect(page.locator('#themes-error')).toBeVisible();
  await page.getByText('Fintech', { exact: true }).click();
  await page.getByText('Investors', { exact: true }).click();
  await expect(page.locator('#themes-error')).toHaveCount(0);
  await expect(page.locator('#audiences-error')).toHaveCount(0);
  await page.getByRole('button', { name: 'Continuar' }).click();
  await page.getByRole('button', { name: 'Agregar co-host' }).click();
  await page.getByRole('button', { name: 'Enviar evento' }).click();
  const cohost = page.locator('section[data-step="3"]');
  await expect(cohost.getByLabel('Nombre de la empresa')).toHaveAttribute('aria-invalid', 'true');
  await cohost.getByLabel('Sitio web (opcional)').fill('http://bad.cl');
  await expect(cohost.getByText(/comience con https/)).toBeVisible();
  await cohost.getByLabel('Sitio web (opcional)').fill('');
  await expect(cohost.getByText(/comience con https/)).toHaveCount(0);
  await cohost.getByRole('button', { name: 'Quitar' }).click();
  await expect(cohost.getByText('Completa este campo.')).toHaveCount(0);
  await page.screenshot({ path: 'tmp/screenshots/event-validation.png' });
});
